import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import basicSsl from '@vitejs/plugin-basic-ssl'
import fs from 'fs'
import path from 'path'

// Check if custom certificates exist (generated by mkcert)
const certPath = path.resolve(__dirname, 'certs/localhost-cert.pem')
const keyPath = path.resolve(__dirname, 'certs/localhost-key.pem')
const hasCustomCert = fs.existsSync(certPath) && fs.existsSync(keyPath)

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Use basicSsl only if custom certificates don't exist
    // ...(!hasCustomCert ? [basicSsl()] : [])
  ],
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },

  // server: {
  //   https: hasCustomCert ? {
  //     key: fs.readFileSync(keyPath),
  //     cert: fs.readFileSync(certPath),
  //   } : true,
  //   port: 5173,
  //   host: true, // Allow external access
  //   headers: {
  //     // Required for WebContainer SharedArrayBuffer support
  //     // Using 'credentialless' instead of 'require-corp' to allow Tailwind and other resources to load
  //     'Cross-Origin-Embedder-Policy': 'credentialless',
  //     'Cross-Origin-Opener-Policy': 'same-origin',
  //   },
  // },
})
