import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import basicSsl from '@vitejs/plugin-basic-ssl'
import fs from 'fs'
import path from 'path'

// Check if custom certificates exist (generated by mkcert)
const certPath = path.resolve(__dirname, 'certs/localhost-cert.pem')
const keyPath = path.resolve(__dirname, 'certs/localhost-key.pem')
const hasCustomCert = fs.existsSync(certPath) && fs.existsSync(keyPath)

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Use basicSsl only if custom certificates don't exist
    // ...(!hasCustomCert ? [basicSsl()] : [])
  ],
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          // Split node_modules into separate chunks
          if (id.includes('node_modules')) {
            // React core
            if (id.includes('react') || id.includes('react-dom') || id.includes('react-router')) {
              return 'react-vendor';
            }
            // Clerk
            if (id.includes('@clerk')) {
              return 'clerk-vendor';
            }
            // CodeMirror
            if (id.includes('@codemirror') || id.includes('@lezer')) {
              return 'codemirror-vendor';
            }
            // Monaco Editor
            if (id.includes('@monaco-editor') || id.includes('monaco-editor')) {
              return 'monaco-vendor';
            }
            // Three.js and WebGL
            if (id.includes('three') || id.includes('ogl')) {
              return 'three-vendor';
            }
            // Terminal
            if (id.includes('@xterm') || id.includes('xterm')) {
              return 'terminal-vendor';
            }
            // WebContainer
            if (id.includes('@webcontainer')) {
              return 'webcontainer-vendor';
            }
            // Other large libraries
            if (id.includes('lucide-react')) {
              return 'icons-vendor';
            }
            // Everything else from node_modules
            return 'vendor';
          }
        },
      },
    },
    chunkSizeWarningLimit: 1500,
  },
  // server: {
  //   https: hasCustomCert ? {
  //     key: fs.readFileSync(keyPath),
  //     cert: fs.readFileSync(certPath),
  //   } : true,
  //   port: 5173,
  //   host: true, // Allow external access
  //   headers: {
  //     // Required for WebContainer SharedArrayBuffer support
  //     // Using 'credentialless' instead of 'require-corp' to allow Tailwind and other resources to load
  //     'Cross-Origin-Embedder-Policy': 'credentialless',
  //     'Cross-Origin-Opener-Policy': 'same-origin',
  //   },
  // },
})
